package br.edu.ifpb.ws.analyzerQuestionsRESTful.enumerations;

public enum TSuggestions {

	TITULO_BEM_DEFINIDO,
	COERENCY_BODY_WITH_TITLE,
	IS_OBJECTIVE,
	IS_OBJECIVE_DC,
	IS_OBJECTIVE_QUESTION_UNIQUE,
	IS_OBJECTIVE_MUCH_CODE,
	IS_CLARITY,
	SHOW_EXAMPLE,
	DETAIL_CONTEXT,
	USING_PROPER_LANGUAGE,
	BE_EDUCADED,
	HOME_WORK_QUESTION,
	SHORT_DESCRIPTION,
	UNIQUE_QUESTION,
	GREAT, TITLE_MEDIO,
	UNDESTANDABLE_DESCRTION;

}
